fcitx5-chewing-git: Switch back to fcitx5-git
This commit practically reverts 220596909eca558b314a1f5d9255afb2779ec255.
The building error with community/fcitx5 was:

/build/fcitx5-chewing-git/src/fcitx5-chewing/src/eim.cpp:135:26: error: conflicting return type specified for ‘virtual const fcitx::CandidateWord& fcitx::{anonymous}::ChewingCandidateList::candidate(int) const’
  135 |     const CandidateWord &candidate(int idx) const override {
      |                          ^~~~~~~~~
In file included from /usr/include/Fcitx5/Core/fcitx/inputpanel.h:24,
                 from /build/fcitx5-chewing-git/src/fcitx5-chewing/src/eim.cpp:24:
/usr/include/Fcitx5/Core/fcitx/candidatelist.h:69:50: note: overridden function is ‘virtual std::shared_ptr<const fcitx::CandidateWord> fcitx::CandidateList::candidate(int) const’
   69 |     virtual std::shared_ptr<const CandidateWord> candidate(int idx) const = 0;
      |                                                  ^~~~~~~~~

Which is related to the following upstream commits:
https://github.com/fcitx/fcitx5-chewing/commit/76498e26001ee2175af32ed43e83e0f1900dd92a
https://github.com/fcitx/fcitx5/commit/8bee2b2b2f62aae19ea9a03af7b2ffe667b8cfca