python-onnxruntime: trigger rebuild
The previous build failed due to out-dated archlinux-keyring on the
build server [1].

> error: chrono-date: signature from "Brett Cornwall <brett@i--b.com>" is unknown trust
> :: File /var/cache/pacman/pkg/chrono-date-3.0.1-1-x86_64.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).

[1] https://build.archlinuxcn.org/~imlonghao/log/python-onnxruntime/2021-08-12T04%3A17%3A01.html