python-etils: update to 0.9.0
The last automatic bump failed with a mysterious issue (broken mirror?)

>  error: failed retrieving file 'python-pytest-subtests-0.9.0-1-any.pkg.tar.zst' from 127.0.0.1:4567 : The requested URL returned error: 404

This package requires manual changes, anyway.